version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      babel-dependencies:
        patterns:
          - "@babel/*"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"


  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
