version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: aplus
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
  web:
    build: .
    command: sbt run
    links:
      - db
    environment:
      DATABASE_URL: postgres://aplus:mysecretpassword@db/aplus
