version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: aplus
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
  web:
    build: .
    command: sbt run
    links:
      - db
    environment:
      DATABASE_URL: postgres://aplus:mysecretpassword@db/aplus
      APP_HOST: localhost:9000
      MAIL_MOCK: "true"
      APPLICATION_SECRET: secret
    ports:
      - "9000:9000"
  admin-db:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    links:
      - db
    ports:
      - "8080:80"
