# Default values here:
# https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/values.yaml
controller:
  service:
    type: NodePort
    externalIPs:
      - 141.94.167.220
      - 141.94.166.107
      - 141.94.164.120
