apiVersion: v1
kind: ConfigMap
metadata:
  name: aplus-config
data:
  APP_HOST: preprod.aplus.incubateur.net
  FEATURE_AUTO_ADD_EXPERT: "false"
  FEATURE_WEEKLY_EMAILS: "false"
  PERSONAL_DATA_RETENTION_IN_MONTHS: "1"
