apiVersion: v1
kind: ConfigMap
metadata:
  name: aplus-restore-script
data:
  restore-script: |
    set -e
    apt-get update
    apt-get install -y postgresql-client-11
    pip install python-openstackclient==5.5.0
    pip install python-swiftclient==3.12.0
    pip install python-keystoneclient==4.2.0

    if [ ! -s /key/key.pub ]
    then
      echo "Stopping: no public key"
      exit 0
    fi
    gpg --no-tty --batch --import /key/key.pub
    gpg --no-tty --batch --allow-secret-key-import --import /private/key.gpg

    # Create token here because they are valid only for a short period of time
    AUTH_TOKEN=$(openstack token issue -c id -f value)

    swift --os-auth-token $AUTH_TOKEN --os-storage-url $STORAGE_URL download $STORAGE_CONTAINER "$BACKUP_FILENAME"

    # Note: here --pinentry-mode loopback is necessary to pass the passphrase
    # Note 2: pg_restore does not read PGDATABASE, it is necessary to put a -d switch
    gpg --no-tty --batch --pinentry-mode loopback --passphrase "$GPG_PRIVATE_KEY_PASSWORD" --recipient "$GPG_RECIPIENT" --decrypt "$BACKUP_FILENAME" | gzip -d | pg_restore -d "$PGDATABASE"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: aplus-restore-job
spec:
  template:
    spec:
      containers:
      - name: aplus-restore
        image: python:3-buster
        env:

        - name: OS_AUTH_URL
          valueFrom:
            secretKeyRef:
              name: ovh-storage-creds
              key: OS_AUTH_URL
        - name: OS_IDENTITY_API_VERSION
          valueFrom:
            secretKeyRef:
              name: ovh-storage-creds
              key: OS_IDENTITY_API_VERSION
        - name: OS_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: ovh-storage-creds
              key: OS_TENANT_ID
        - name: OS_TENANT_NAME
          valueFrom:
            secretKeyRef:
              name: ovh-storage-creds
              key: OS_TENANT_NAME
        - name: OS_USERNAME
          valueFrom:
            secretKeyRef:
              name: ovh-storage-creds
              key: OS_USERNAME
        - name: OS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ovh-storage-creds
              key: OS_PASSWORD
        - name: OS_REGION_NAME
          valueFrom:
            secretKeyRef:
              name: ovh-storage-creds
              key: OS_REGION_NAME

        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: aplus-db-app-secret
              key: DATABASE_NAME
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: aplus-db-app-secret
              key: DATABASE_HOST
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: aplus-db-app-secret
              key: DATABASE_PASSWORD
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: aplus-db-app-secret
              key: DATABASE_USER

        - name: BACKUP_FILENAME
          value: "CHANGEME.pgdump.gz.gpg"
        - name: GPG_RECIPIENT
          valueFrom:
            secretKeyRef:
              name: aplus-backup-pub-key
              key: GPG_RECIPIENT
        - name: GPG_PRIVATE_KEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: aplus-backup-priv-key
              key: GPG_PRIVATE_KEY_PASSWORD
        - name: STORAGE_CONTAINER
          value: "aplusprodbackup"
        - name: STORAGE_URL
          valueFrom:
            secretKeyRef:
              name: ovh-storage-creds
              key: STORAGE_URL

        volumeMounts:
        - name: script
          mountPath: "/script"
        - name: public-key
          mountPath: "/key"
        - name: private-key
          mountPath: "/private"
        command: ["bash",  "/script/run.sh"]
      volumes:
      - name: script
        configMap:
          name: aplus-restore-script
          items:
          - key: restore-script
            path: "run.sh"
      - name: public-key
        secret:
          secretName: aplus-backup-pub-key
          items:
          - key: GPG_PUBLIC_KEY
            path: "key.pub"
      - name: private-key
        secret:
          secretName: aplus-backup-priv-key
          items:
          - key: GPG_PRIVATE_KEY
            path: "key.gpg"
      restartPolicy: Never
  backoffLimit: 0
