name: Docker

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S')"
    - name: Get Short SHA
      id: shortsha
      run: echo "::set-output name=shortsha::$(git rev-parse --short HEAD)"
        
    - name: Build image
      run: docker build . --tag betagouv/aplus:commit-${{ steps.date.outputs.date }}-${{ steps.shortsha.outputs.shortsha }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Push image
      run: docker push betagouv/aplus:commit-${{ steps.date.outputs.date }}-${{ steps.shortsha.outputs.shortsha }}
